### ISSUE TITLE
Add method to flush report results from cache

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/geoprocessing#12]

**Comment by danyocum** [comment]
npm run clear-results

User specifies the name of the function of the results to clear or 'all' to clear all the cached results. To find the name of the dynamodb table, the script finds the package.json and extracts the project name, then wraps with gp-{$project-name}-tasks, which is how it is generated in the create:function script. 

Note: in the example project when I was testing it, I added the ability to ask the user for the table name if it couldn't find a dynamodb table with the name of the current project. Is this a security bug? Right now it's not, because we're the only ones able to run the clear-results, but we plan to be able to let others run the tool, and then they could theoretically clear the cache results by guessing the name of another project...Not sure how likely that is, but thought we should discuss.

**Comment by underbluewaters** [comment]
I wouldn't consider it a security risk because the command will be called with AWS credentials which presumably don't have access where they shouldn't. 3rd party developers will be deploying tools with their own aws accounts.

I do worry though that the command might clear the wrong table unintentionally. Is there a common case where the library wouldn't be able to find the table? I don't see how since that would mean any deployed functions couldn't save and retrieve results.

**Comment by danyocum** [comment]
The only time it happens is if you run it from inside example-project (in @seasketch/geoprocessing), which I was doing while testing it...But it's pretty unlikely otherwise. And now that it's in and working, I have no problem getting rid of the functionality (unless/until we find a different case where it's useful).

**Comment by underbluewaters** [comment]
Yeah I'd say just drop it.

**Comment by danyocum** [comment]
yep
-D
