### ISSUE TITLE
Improve geoblaze accuracy

### ISSUE THREAD

**Issue by twelch** [seasketch/geoprocessing#156]
Issue: Geoblaze uses a centerline algorithm to determine if polygon overlaps with a raster cell.  A raster cell will be missed if the polygon doesn't overlap with the centerline of the cell, which happens pretty regularly for datasets with larger raster cells (say 1-5km), and small sketches (small local nearshore sketches around 1 square km in size).

Users should be able to design at the size that makes sense to them, even if it's small and expect relatively accurate results without understanding the limitations of the software.  The swing in statistics if an overlapping cell is missed can be significant, especially if the data is sparse and overlapping with even one cell is meaningful.

Goal: add support for "contains" algorithm that include a raster cell in the overlap if any part of the polygon overlaps with the raster cell.

Risk of doing this:
* It may be much slower to calculate overlap with a raster cell (box) instead of centerline.
* It may give false positives.  The data may be summarized to a large raster cell but it's not guaranteed that the phenomena is evenly distributed or that the MPA should take on the value of the entire cell.

Let's at least understand what it would take to implement, and confirm at least one use case where it should be used.

Tasks:
- [ ] add support for "contains" method to geoblaze library (may already be nascent support?), and allow user to choose which algorithm is used.
- [x] add unit tests
- [x] upgrade geoprocessing library to new geoblaze version, expose ability to choose which method to use, add unit tests demonstrating.
- [x] test in a current gp project.

**Comment by DanielJDufour** [comment]
Thought about this a little more and wanted to jot down some questions and notes.
- What specific statistics are being calculated here?

Here's a few solutions I'm thinking about, building on top of your proposal above:
- Add the concept of "resolution" or "virtual resampling" to GeoBlaze and/or the underlying [dufour-peyton-intersection](https://github.com/geotiff/dufour-peyton-intersection).  I basically mean being able to adjust how many horizontal lines to drop per pixel row.  It will pretend as if we resampled the raster without spending the extra CPU ops and memory to actually do it.  Currently we drop one line.  Dropping two along the top and bottom edges would be an improvement for sure.  But maybe we can take it further and be able to drop even more when the geometry is really small.  For example, if the geometry bbox takes up 1/10th the height of a pixel, perhaps drop 10 or more lines per pixel row, just to make sure it intersects at least one line.  I believe we could also automate the comparison of pixel and geometry sizes, so GeoBlaze can internally determine how many lines to drop without the need for additional user input.
- Just use TurfJS.  GeoBlaze was originally created in large part because converting every pixel to a GeoJSON polygon and running point-in-polygon operations on them via TurfJS was too slow (TurfJS wasn't built for rasters).  But that was because we had potentially a lot of intercepting pixels.  If the geometry only intersects one or a few pixels, then the performance of using TurfJS will probably be okay.  The issue with this is that we would have to rewrite how the statistics are calculated for relatively small geometries.  The statistics currently rely on [calc-stats](https://www.npmjs.com/package/calc-stats) which assumes an iterable of values for equally-sized pixels.  If we were to take this route, we would probably want to factor in the size of each intersecting/overlapping area.  

More later :-)

**Comment by twelch** [comment]
I like the idea of having extra horizontal lines per pixel row.  I imagined top, middle, and bottom.  More than that and I've been thinking the raster should really be resampled beforehand in the prep.

95% of the time in geoprocessing reports we are just doing a polygon overlap count or sum.  Because what we are reporting is percent overlap or (count/sum of cells within the polygon / total count/sum of cells in the whole raster).

On occasion, like for sketch overlap with bathymetry we want like the min, max, avg.

**Comment by DanielJDufour** [comment]
Good point on preprocessing.  I'm a big fan of preprocessing/precomputing when it's possible :-)  I think doing top, middle and bottom would be very achievable.

I also wanted to put an idea out there and see what you think.  I'm not sure it's the solution, but might be.  If SeaSketch users care about the percent overlap and not necessarily the intermediate values like sum and count that it took to get there, then I'm wondering if maybe we should create a new function for geoblaze called frequency.  It would be used like this:
```js
import geoblaze from 'geoblaze';

geoblaze.frequency('https://example.org/temperature.tif', geojson, {
    get_class: ({ pixel_values }) => {
        const value = pixel_values[0]; // single band
        if (value === fish_present_value) {
            return 'fish';
        } else {
            // value is a no_data_value or not a value indicating fish are present
            return 'no_fish';
        }
    }
});

// result
{
    "fish": 0.7,
    "no_fish": 0.3
}
```

Looking forward to your thoughts.

**Comment by twelch** [comment]
It's a good thought.  Yes it's almost always percent overlap we care about.  But it's not percentage by class within the overlap, it's percent of all the raster value that is within the polygon.

So if the raster is say total fish biomass (volume) per cell,  we would precalculate the total sum of all fish biomass for the whole raster.

Then the percent overlap is:
`sum of biomass within polygon / total sum biomass of raster`

I'm not seeing that frequency will get us this without fetching the whole raster.

**Comment by twelch** [comment]
I'm going to close out this issue as mostly complete.  The virtual resampling can be revisited as needed.

**Comment by DanielJDufour** [comment]
Working on virtual resampling, but wanted to note that an additional optimization (perhaps over engineering) for min, max, and range calculations would be to run an identify at each vertex of a geometry.  At least that would run in O(N) linear time.
