### ISSUE TITLE
Improve geoblaze integration with geoprocessing library

### ISSUE THREAD

**Issue by twelch** [seasketch/geoprocessing#161]
The geoprocessing library uses a dated (pre geoblaze 1.0) method to fetch cloud-optimized geotiff's for use with geoblaze using georaster directly.  This work can likely be streamlined.

- COG loader - https://github.com/seasketch/geoprocessing/blob/dev/packages/geoprocessing/src/dataproviders/cog.ts#L24
- Example of toolbox function using geoblaze - https://github.com/seasketch/geoprocessing/blob/dev/packages/geoprocessing/src/toolbox/overlapRaster.ts#L101

Tasks:
- [ ] Review and refactor cog.ts to use latest geoblaze API and reduce bespoke code.
- [ ] Potentially switch to loading rasters from filesystem for tests, instead of running a web server, which complicates test runner.

It would be valuable to discuss how the window is calculated and then used, and how it affects what resolution of raster is returned. 
 .  In most/all cases we want the highest resolution raster to be used and results not to vary, but it's not clear what logic is used to determine what raster resolution is returned.

**Comment by DanielJDufour** [comment]
I believe the most recent version of GeoBlaze gets the highest resolution.  However, I think adding some tests verifying that would be awesome.

**Comment by DanielJDufour** [comment]
I believe this code: https://github.com/GeoTIFF/geoblaze/blob/master/src/get/get.module.js#L67
is passing in a height and width to georaster (which passes to geotiffjs).  It's passing in the highest res height and width (in pixels) of the aoi to make sure georaster/geotiff.js know to use the highest res image within the geotiff.

It's counter-intuitive for sure, but I think part of the reason is to future proof, in case the next version of georaster tries to "optimize" data fetching.

**Comment by DanielJDufour** [comment]
I think a part of this work could include:
- Adding/Improving GeoBlaze documentation around COGs
- Adding a few examples, maybe https://observablehq.com/ notebooks demonstrating this new functionality
