### ISSUE TITLE
Truncate numbers in gp function output and possibly sketch input

### ISSUE THREAD

**Issue by twelch** [seasketch/geoprocessing#173]
Need:

Different systems can produce slightly different results in geoprocessing functions for the same inputs when using Turf.  The differences are usually beyond 6 significant digits, which is not relevant.  But this can mean that smoke test output is different and two developers working on the same project can cause thrashing.

Large decimal numbers are also known to be an issue within Turf due to the limitation of Javascript to handle large floating point numbers.

Solution:

Truncate analysis results to only the number of significant digits needed. 
Analysis results such as area don't need more than 6 significant.

Even lat/lon coordinates don't need so many significant digits and Turf and dependencies actually have a hard time with them.  [More info](https://github.com/Turfjs/turf/issues/2409) and [here](https://github.com/Turfjs/turf/issues/2258) and possible solution of using https://turfjs.org/docs/#truncate

More info on floating point:
* https://floating-point-gui.de/

**Comment by avmey** [comment]
@twelch Seems like Turf `truncate(x)` truncates to x digits after the decimal. I'm assuming this isn't what we want for values coming out of `overlapFeatures()` because some of our results are very small (e^-7) and would be truncated to 0. So instead we're using 6 significant digits to simplify results.

This is fine, just letting you know that the process will be different between latlon truncation and our analysis rounding to significant digits (using the inbuilt `.toPrecision(6)`). Also happy to hear any other thoughts on this.

**Comment by twelch** [comment]
My first thought is that I think for very small values beyond 6 decimal digits, we just wouldn't use truncate. And if in practice that still creates noise out at 7-8-9 digits we want to cut out, then we could offer a second option to change the precision.

**Comment by avmey** [comment]
I like that idea. I've added logic to avoid truncating very small values. We can see if we still get any differences cropping up.
