### ISSUE TITLE
Upgrade AWS-SDK from v2 to v3

### ISSUE THREAD

**Issue by avmey** [seasketch/geoprocessing#211]
Need to update AWS-SDK from version 2 to 3

After migration:
- aws-sdk should be excluded from build (via esbuild externals).  It's only included because node 20 lambdas don't already include v2 anymore, only v3.

**Comment by twelch** [comment]
Also

- WebSocket not part of aws-cdk-lib yet. Need to add alpha library - https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-apigatewayv2-alpha.WebSocketApi.html
- Bootstrapping (https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html) - AWS CDK v1 supported two bootstrapping templates, legacy and modern. CDK v2 supports only the modern template. An environment that has been bootstrapped using the legacy template can (and must) be upgraded to use the modern template for use with CDK v2 by re-bootstrapping. So once the first project is redeployed for a given region, we may not be able to make code changes to other projects without upgrading as well.

**Comment by twelch** [comment]
- dynamodb examples - https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javascriptv3/example_code/dynamodb/actions/scan.js

**Comment by twelch** [comment]
It's import to use the DocumentClient wrapper because it allows you to use natural javascript types
* https://stackoverflow.com/questions/57804745/difference-between-aws-sdk-dynamodb-client-and-documentclient
* https://stackoverflow.com/questions/57804745/difference-between-aws-sdk-dynamodb-client-and-documentclient
* Examples of use - https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javascriptv3/example_code/dynamodb/actions/document-client/scan.js
