### ISSUE TITLE
Switch to full turf >= 6.2.0 with tree shaking

### ISSUE THREAD

**Issue by twelch** [seasketch/geoprocessing#29]
I noticed that 6.2.0 is supposed to support tree shaking.  Final bundle size would. need to be compared, but might be worth trying to switch over to the full package.  It's tedious to manage each individual sub-package.  Thoughts @underbluewaters?

https://github.com/Turfjs/turf/blob/master/CHANGELOG.md#620

**Comment by underbluewaters** [comment]
I'm not convinced it's a good idea to export big packages like turf, d3, etc into the environment for project implementations. It adds a burden to us to keep those packages up to date and also would then create difficult decisions about when to include breaking changes in those libraries. I've had to do things like use particular versions of @turf/intersect and other functions in the past to get around dataset-specific edge cases so I definitely see value in picking and choosing particular packages. In the future if we need to upgrade gpx on an old project it could be a good thing if we can get newer build-script related stuff without also being forced to upgrade big libraries that have breaking changes. 

Right now the framework includes @turf/area because it's used by the sketchArea function, but it's really an accident that the turf function itself is exposed. My vote would be to keep included dependencies limited to those needed for specific functions we want to export and support. At least for now...It's probably going to be an ongoing discussion how much of a "batteries included" system we want this to be.

**Comment by twelch** [comment]
Good thoughts.  Devils advocate for a moment

Clarify main benefit I see:
* It puts the basic functions at your fingertips, the disruption to install deps is diminished, and if shaking works you only get what you need in the final bundle.
* Upgrading one dependency is simpler than many.  For the most part it should 'just work' and tests should catch issues.

> export big packages like turf, d3, etc into the environment for project implementations. It adds a burden to us to keep those packages up to date

Does it?  Can't we just upgrade when it's convenient and we need a newer method?

> I've had to do things like use particular versions of @turf/intersect and other functions in the past to get around dataset-specific edge cases so I definitely see value in picking and choosing particular packages.

Can't you still do this?  For edge cases you could import individual older turf packages for specific uses alongside the full turf library.  Then you can leave a clue of why you're doing it in the code and cue to keep trying to get back to the latest.

> In the future if we need to upgrade gpx on an old project it could be a good thing if we can get newer build-script related stuff without also being forced to upgrade big libraries that have breaking changes.

This could be one reason to let each project import its own turf methods, d3 etc. (whether bundle or individual), not rely on what versions the gpx project uses.
