### ISSUE TITLE
Add rate limiting to GeoprocessingHandler

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/geoprocessing#3]
Handlers should have a sane default rate limit and also respect options specified by the author. This may be possible to implement using API Gateway, but if not it could be done in the handler code.

**Comment by danyocum** [comment]
@underbluewaters what should the rate limit/burst limit be?

**Comment by underbluewaters** [comment]
This might require a little research. There are a couple major use cases for rate limiting, not entirely related.

1. Is purely automated abuse. We want humans running these, so maybe limit to 30 per minute or so? This may already be handle sufficiently by API Gateway. I'm not sure what they have in place.
2. Would be to prevent cost overruns. It would be awesome if we could specify in a GeoprocessingHandler a dollar amount not to exceed. Maybe pull data from cloudwatch metrics and shutdown the service if it exceeds $10 in a month (by default). We wouldn't want to slow down requests for this though. Maybe it could be a periodic cron lambda that reads the stats every hour or so and sets a flag in dynamodb to reject requests. Code for checking should probably be highly modular because when we get to container-based tasks we will probably want to check on every run since they can cost a few dollars each time.

**Comment by danyocum** [comment]
It's easy to set the method-level throttling for a stage on the api gateway, by adding this to createStack apigateway.RestApi:

        deployOptions: {
          throttlingBurstLimit: 20,
          throttlingRateLimit: 40,
        },

these options are requests per second. I was thinking of the workshop use case, where, for example, there were 25 people sitting in a room and will said "ok, view the reports". There's a chance all 25 people would post those requests within 1 second of each other...and if we had a limit of 30/minute some of them would get rejected. That's why I've arbitrarily chosen 40 at the moment (burst rate is half the rate limit because that's the way the defaults are)...

Does that sound reasonable? Too high?

**Comment by underbluewaters** [comment]
I think that seems good. Especially if it's something that can be customized in the GeoprocessingHandler options. Safe bet would be to have high defaults for rate-limiting, and then the cost limiting is where authors can be more conservative. I guess that opens up the possibilities for real dos'ing but that seems less of a risk than someone being surprised by a big bill.

**Comment by twelch** [comment]
These limits are in place, closing
